<%@ page session="true" language="java" contentType="text/html; charset=euc-kr" pageEncoding="euc-kr"%><%/*** 프로젝트명	: 하도급거래 서면실태조사 지원을 위한 개발용역 사업* 프로그램명	: help_board_view.jsp* 프로그램설명	: 조사사이트 도움말 조회/등록/수정* 프로그램버전	: 1.0.1* 최초작성일자	: 2009년 05월* 작 성 이 력       :*=========================================================*	작성일자		작성자명				내용*=========================================================*	2009-05-00	정광식       최초작성*	2015-12-30	정광식	DB변경으로 인한 인코딩 변경*	2016-01-20 	민현근	DB변경으로 인한 인코딩 변경*/%>
<%@ page import="java.sql.*"%><%@ page import="java.util.*"%><%@ page import="ftc.util.*"%><%@ page import="ftc.db.ConnectionResource"%><%@ page import="ftc.db.ConnectionResource2"%><%@ page import="java.text.DecimalFormat"%>

<%@ include file="/hado/wTools/inc/WB_I_Global.jsp"%><%@ include file="/hado/wTools/inc/WB_I_chkMngSession.jsp"%><%/*---------------------------------------- Variable Difinition ----------------------------------------*/	String sTableName = "";
	String sErrorMsg = "";	String sSQLs = "";
	int nNewNo = 0;
	String q_No = request.getParameter("no")==null ? "":request.getParameter("no").trim();	String sLink = "cmd=insert";	if(q_No != null && (!q_No.equals("new")) ) {		sLink = "cmd=edit";	}
	ConnectionResource resource = null;	Connection conn = null;	PreparedStatement pstmt = null;	ResultSet rs = null;	ArrayList arrTypeName = new ArrayList();
	String d_Class = "";	String d_Type = "";	String d_Subject = "";	String d_Question = "";	String d_Answer = "";/*-----------------------------------------------------------------------------------------------------*/
/*=================================== Record Selection Processing =====================================*/	if(q_No != null && (!q_No.equals("new")) ) {		try {			resource = new ConnectionResource();			conn = resource.getConnection();
			sSQLs ="SELECT * \n";			sSQLs+="FROM HADO_TB_FAQ_Board \n";			sSQLs+="WHERE board_No=? \n";			sSQLs+="	AND Delete_Flag='N' \n";
			pstmt = conn.prepareStatement(sSQLs);			pstmt.setString(1,q_No);			rs = pstmt.executeQuery();	  
			while (rs.next()) {				/* 2015-12-30	정광식		DB변경으로 인한 인코딩 변경				d_Class		= new String(StringUtil.checkNull(rs.getString("Board_Class")).trim().trim().getBytes("ISO8859-1"), "EUC-KR" );				d_Type		= new String(StringUtil.checkNull(rs.getString("Board_Type")).trim().trim().getBytes("ISO8859-1"), "EUC-KR" );				d_Subject	= new String(StringUtil.checkNull(rs.getString("Board_Subject")).trim().trim().getBytes("ISO8859-1"), "EUC-KR" );				d_Question	= new String(StringUtil.checkNull(rs.getString("Board_Question")).trim().trim().getBytes("ISO8859-1"), "EUC-KR" ).replaceAll("\"","˝").replaceAll("'","´").replaceAll("\r\n","<br/>");				d_Answer	= new String(StringUtil.checkNull(rs.getString("Board_Answer")).trim().trim().getBytes("ISO8859-1"), "EUC-KR" ).replaceAll("\"","˝").replaceAll("'","´").replaceAll("\r\n"," <br/> ");				*/				d_Class = rs.getString("Board_Class").trim();				d_Type = rs.getString("Board_Type").trim();				d_Subject = rs.getString("Board_Subject").trim();				d_Question = rs.getString("Board_Question").trim().replaceAll("\"","˝").replaceAll("'","´").replaceAll("\r\n","<br/>");				d_Answer = rs.getString("Board_Answer").trim().trim().replaceAll("\"","˝").replaceAll("'","´").replaceAll("\r\n"," <br/> ");			}			rs.close();		} catch(Exception e) {			e.printStackTrace();		} finally {			if ( rs != null ) try{rs.close();}catch(Exception e){}			if ( pstmt != null ) try{pstmt.close();}catch(Exception e){}			if ( conn != null ) try{conn.close();}catch(Exception e){}			if ( resource != null ) resource.release();		}	}	try {		resource = new ConnectionResource();		conn = resource.getConnection();
		sSQLs ="SELECT Board_Type \n";		sSQLs+="FROM HADO_TB_FAQ_BOARD \n";		sSQLs+="GROUP BY Board_Type \n";		pstmt = conn.prepareStatement(sSQLs);		rs = pstmt.executeQuery();	  
		while (rs.next()) {			arrTypeName.add(rs.getString("Board_Type"));		}		rs.close();	}	catch(Exception e){		e.printStackTrace();	}	finally {		if ( rs != null ) try{rs.close();}catch(Exception e){}		if ( pstmt != null ) try{pstmt.close();}catch(Exception e){}		if ( conn != null ) try{conn.close();}catch(Exception e){}		if ( resource != null ) resource.release();	}/*=====================================================================================================*/%>
<script type="text/javascript">//<![CDATA[content = "";
content+="<div id='viewWinTop'>";content+="	<ul class='lt'>";content+="		<li class='fr'><a href=javascript:closeViewWin('divView') class='sbutton'>창닫기</a></li>";content+="	</ul>";content+="</div>";
content+="<div id='viewWinTitle'>도움말 게시물 등록</div>";
content+="<table class='ViewResultTable' align='center'>";content+="<form action='help_board_Query.jsp?<%=sLink%>' method='post' name='MemberInform' target='procFrame'>";content+="	<tr>";content+="		<th>노출구분</th>";content+="		<td><select name='mClass'>";content+="				<option value='A' <%if(d_Class!=null && d_Class.equals("A")) {%>selected<%}%>>전체사업자</option>";content+="				<option value='O' <%if(d_Class!=null && d_Class.equals("O")) {%>selected<%}%>>원사업자</option>";content+="				<option value='S' <%if(d_Class!=null && d_Class.equals("S")) {%>selected<%}%>>수급사업자</option>";content+="			</select>";content+="			<input type='hidden' name='mNo' value='<%=q_No%>'>";content+="		</td>";content+="	</tr>";content+="	<tr>";content+="		<th>유형</th>";content+="		<td><select name='mType1'>";content+="				<option value=''>유형추가==></option>";<%for(int ni = 0; ni < arrTypeName.size(); ni++) {%>content+="				<option value='<%=arrTypeName.get(ni)%>' <%if(d_Type!=null && arrTypeName.get(ni)!=null & d_Type.equals(arrTypeName.get(ni)) ) {%>selected<%}%>><%=arrTypeName.get(ni)%></option>";<%}%>content+="			</select> ";content+="			| 유형추가 : <input type='text' name='mType2' value='' class='s_input'>";content+="		</td>";content+="	</tr>";content+="	<tr>";content+="		<th>담당과명</th>";content+="		<td><input type='text' name='mDeptName' value='<%=session.getAttribute("ckDeptName")+""%>' class='s_input'></td>";		content+="	</tr>";content+="	<tr>";content+="		<th>제목</th>";content+="		<td><input type='text' name='mSubject' value='<%= d_Subject%>' class='mx_input'></td>";		content+="	</tr>";content+="	<tr>";content+="		<th>질문내용</th>";content+="		<td><textarea name='mQuestion' id='mQuestion' class='board_textarea' wrap='PHYSICAL'><%=d_Question%></textarea></td>";		content+="	</tr>";content+="	<tr>";content+="		<th>답변내용</th>";content+="		<td><textarea name='mAnswer' id='mAnswer' class='board_textarea' wrap='PHYSICAL'><%=d_Answer%></textarea></td>";content+="	</tr>";content+="</form>";content+="</table>";
content+="<div id='divViewWinbutton'>";content+="	<ul class='lt'>";content+="		<li class='fl'><a href=javascript:top.savef(document.MemberInform) class='sbutton'>정보등록</a></li>";content+="		<li class='fl'><a href=javascript:top.deluserf(document.MemberInform) class='sbutton'>정보삭제</a></li>";content+="		<li class='fr'><a href=javascript:top.closeViewWin('divView') class='sbutton'>창닫기</a></li>";content+="	</ul>";content+="</div>";
top.document.getElementById("divView").innerHTML = content;top.setNowProcessFalse();
top.boardTextreplace();//]]</script>
<%@ include file="/hado/wTools/inc/WB_I_Function.jsp"%>