<%@ page session="true" language="java" contentType="text/html; charset=euc-kr" pageEncoding="euc-kr"%><%/*** 프로젝트명	: 하도급거래 서면실태조사 지원을 위한 개발용역 사업* 프로그램명	: help_board_Search.jsp* 프로그램설명	: 도움말 게시물 검색* 프로그램버전	: 1.0.1* 최초작성일자	: 2009년 05월* 작 성 이 력       :*=========================================================*	작성일자		작성자명				내용*=========================================================*	2009-05-00	정광식       최초작성*	2015-12-30	정광식		DB변경으로 인한 인코딩 변경*/%>
<%@ page import="java.sql.*"%><%@ page import="java.util.*"%><%@ page import="ftc.util.*"%><%@ page import="ftc.db.ConnectionResource"%><%@ page import="ftc.db.ConnectionResource2"%><%@ page import="java.text.DecimalFormat"%>

<%@ include file="/hado/wTools/inc/WB_I_Global.jsp"%><%@ include file="/hado/wTools/inc/WB_I_chkMngSession.jsp"%><%/*---------------------------------------- Variable Difinition ----------------------------------------*/	String q_SearchClass = request.getParameter("searchclass")==null ? "":request.getParameter("searchclass").trim();	String q_SearchType = request.getParameter("searchtype")==null ? "":request.getParameter("searchtype").trim();	String q_SearchText 	= request.getParameter("searchtext")==null ? "":request.getParameter("searchtext").trim();
	ArrayList arrNo = new ArrayList();	ArrayList arrDate = new ArrayList();	ArrayList arrType = new ArrayList();	ArrayList arrDept = new ArrayList();	ArrayList arrCount = new ArrayList();	ArrayList arrSubj = new ArrayList();	ArrayList arrClass = new ArrayList();
	ConnectionResource resource = null;	Connection conn = null;	PreparedStatement pstmt = null;	ResultSet rs = null;
	String sSQLs = "";
	DecimalFormat formater = new java.text.DecimalFormat("###,###,###,###,###,###,###,###");/*-----------------------------------------------------------------------------------------------------*/
/*=================================== Record Selection Processing =====================================*/	try {		resource = new ConnectionResource();		conn = resource.getConnection();
		sSQLs ="SELECT BOARD_NO,TO_CHAR(BOARD_DATE,'yyyy-mm-dd') BOARD_DATE,BOARD_CLASS,BOARD_TYPE, \n";		sSQLs+="	BOARD_DEPTNAME,BOARD_SUBJECT,BOARD_VCOUNT \n";		sSQLs+="FROM HADO_TB_FAQ_BOARD \n";		sSQLs+="WHERE Delete_Flag = 'N' \n";
		if(q_SearchClass!=null && (!q_SearchClass.equals("")) ) {						sSQLs+="	AND Board_Class='"+new String(q_SearchClass.getBytes("EUC-KR"), "ISO8859-1" )+"' \n";
		}
		if(q_SearchType!=null && (!q_SearchType.equals("")) ) {			/* 2015-12-30	정광식		DB변경으로 인한 인코딩 변경
			sSQLs+="	AND (Board_Type='"+new String(q_SearchType.getBytes("EUC-KR"), "ISO8859-1" )+"' \n";			*/			sSQLs+="	AND (Board_Type='"+q_SearchType+"' \n";
		}
		if(q_SearchText!=null && (!q_SearchText.equals("")) ) {			/* 2015-12-30	정광식		DB변경으로 인한 인코딩 변경
			sSQLs+="	AND (Board_Subject LIKE '%"+new String(q_SearchText.trim().getBytes("EUC-KR"), "ISO8859-1" )+"%' \n";			sSQLs+="		OR Board_Question LIKE '%"+new String(q_SearchText.trim().getBytes("EUC-KR"), "ISO8859-1" )+"%') \n";			*/			sSQLs+="	AND (Board_Subject LIKE '%"+q_SearchText+"%' \n";			sSQLs+="		OR Board_Question LIKE '%"+q_SearchText+"%') \n";
		}		sSQLs+="ORDER BY Board_No DESC \n";
		pstmt = conn.prepareStatement(sSQLs);		rs = pstmt.executeQuery();	  
		while (rs.next()) {			arrNo.add( rs.getString("Board_No")==null ? "":rs.getString("Board_No").trim() );			arrDate.add( rs.getString("Board_Date")==null ? "":rs.getString("Board_Date").trim() );			arrClass.add( rs.getString("Board_Class")==null ? "":rs.getString("Board_Class").trim() );			/* 2015-12-30	정광식		DB변경으로 인한 인코딩 변경			arrType.add(new String(StringUtil.checkNull(rs.getString("Board_Type")).trim().getBytes("ISO8859-1"), "EUC-KR" ));			arrDept.add(new String(StringUtil.checkNull(rs.getString("Board_DeptName")).trim().getBytes("ISO8859-1"), "EUC-KR" ));			arrSubj.add(new String(StringUtil.checkNull(rs.getString("Board_Subject")).trim().getBytes("ISO8859-1"), "EUC-KR" ));			*/			arrType.add( rs.getString("Board_Type")==null ? "":rs.getString("Board_Type").trim() );			arrDept.add( rs.getString("Board_DeptName")==null ? "":rs.getString("Board_DeptName").trim() );			arrSubj.add( rs.getString("Board_Subject")==null ? "":rs.getString("Board_Subject").trim() );			arrCount.add( rs.getString("Board_VCount")==null ? "":rs.getString("Board_VCount").trim() );		}		rs.close();	} catch(Exception e){		e.printStackTrace();	} finally {		if ( rs != null ) try{rs.close();}catch(Exception e){}		if ( pstmt != null ) try{pstmt.close();}catch(Exception e){}		if ( conn != null ) try{conn.close();}catch(Exception e){}		if ( resource != null ) resource.release();	}/*=====================================================================================================*/%><script type="text/javascript">//<![CDATA[
	content = "";	
	content+="<table id='divButton'>";	content+="	<tr>";	content+="		<td>검색된 게시물수 : <%=formater.format(arrNo.size())%>개</strong></td>";	content+="	</tr>";	content+="</table>";		content+="<table class='resultTable'>";	content+="	<tr>";	content+="		<th>순번</th>";	//content+="		<th>등록일자</th>";	content+="		<th>노출구분</th>";	content+="		<th>질문유형</th>";	content+="		<th>담당과명</th>";	content+="		<th>제목</th>";	content+="	</tr>";	
	<%if( arrNo.size()>0 ) {		for(int ni=0;ni<arrNo.size();ni++) {%>	content+="	<tr onMouseOver='tbRow_Over(this)' onMouseOut='tbRow_Out(this)'>";	content+="		<td align=right><%=ni+1%></td>";	//content+="		<td><%= arrDate.get(ni)%></td>";	content+="		<td><%if(arrClass.get(ni).equals("O")) {%>원사업자<%}else if(arrClass.get(ni).equals("S")) {%>수급사업자<%}else{%>전체사업자<%}%></td>";	content+="		<td><%=arrType.get(ni)%></td>";	content+="		<td><%=arrDept.get(ni)%></td>";	content+="		<td><a href=javascript:top.view('<%=arrNo.get(ni)%>')><%=arrSubj.get(ni)%></a></td>";	content+="	</tr>";	<%	}	}else {%>	content+="	<tr>";	content+="		<td colspan='6' class='noneResultset'>검색 결과가 없습니다</td>";	content+="	</tr>";	<%}%>	content+="</table>";	
	content+="<div id='divButton'>";	content+="	<ul class='lt'>";	content+="		<li class='fr'><a href=javascript:top.view('new') class='sbutton'>게시물 등록</a></li>";	content+="	</ul>";	content+="</div>";	
	top.document.getElementById("divResult").innerHTML = content;	top.setNowProcessFalse();//]]
</script><%@ include file="/hado/wTools/inc/WB_I_Function.jsp"%>