<%@ page session="true" language="java" contentType="text/html; charset=utf-8" pageEncoding="utf-8"%><%/*** 프로젝트명	: 하도급거래 서면실태조사 지원을 위한 개발용역 사업* 프로그램명	: SOent_Violate_26s.jsp* 프로그램설명	: 원사업자 검색 (팝업)* 프로그램버전	: 1.0.1* 최초작성일자	: 2009년 05월* 작 성 이 력       :*=========================================================*	작성일자		작성자명				내용*=========================================================*	2009-05-00	정광식       최초작성*	2012-11-12	정광식		Database 성능향상을 위하여 2012년부터 원사업자 및 원사업자 응답 테이블 분리*	2016-01-05	정광식		DB변경으로 인한 인코딩 변경*/%>
<%@ page import="java.sql.*"%><%@ page import="java.util.*"%><%@ page import="ftc.util.*"%><%@ page import="ftc.db.ConnectionResource"%><%@ page import="ftc.db.ConnectionResource2"%>
<%@ include file="/hado/wTools/inc/WB_I_Global.jsp"%><%@ include file="/hado/wTools/inc/WB_I_chkMngSession.jsp"%><%/*---------------------------------------- Variable Difinition ----------------------------------------*/	String sWGB = StringUtil.checkNull(request.getParameter("wgb"));	String sSGB = StringUtil.checkNull(request.getParameter("sgb"));	String sCompName = StringUtil.checkNull(request.getParameter("violatecomp"));	String sCompNo = StringUtil.checkNull(request.getParameter("violatecompno"));	String sCYear = StringUtil.checkNull(request.getParameter("cyear"));
	ConnectionResource resource = null;	Connection conn = null;	PreparedStatement pstmt = null;	ResultSet rs = null;
	String sSQLs = "";	ArrayList arrOName = new ArrayList();	ArrayList arrOMngNo = new ArrayList();	ArrayList arrOGB = new ArrayList();/*-----------------------------------------------------------------------------------------------------*//*=================================== Record Selection Processing =====================================*/	/* 업데이트 일자 : 2012년 11월 12일	   작성자 : 정광식	   비고 : Database 성능향상을 위하여 2012년부터 원사업자 및 원사업자 응답 테이블 분리			  HADO_TB_Oent --> HADO_TB_Oent_2012 */	int currentYear = st_Current_Year_n;	if( !sCYear.equals("") ) {		currentYear = Integer.parseInt(sCYear);	}
	String OentInfo_TbNm = "HADO_TB_Oent";	if( currentYear>2011 ) {		OentInfo_TbNm = "HADO_TB_Oent_"+currentYear;	}
	try {		resource = new ConnectionResource();		conn = resource.getConnection();
		sSQLs ="SELECT REPLACE(Oent_Name,' ','_') Oent_Name, Mng_No, Oent_GB \n";		sSQLs+="FROM "+OentInfo_TbNm+" \n";		sSQLs+="WHERE SUBSTR(Mng_No,-5)<>'99999' \n";		sSQLs+="	AND LENGTH(Mng_No)>4 \n";		if( !sWGB.equals("") ) {			sSQLs+="	AND Oent_GB='"+sWGB+"' \n";		}		if( !sSGB.equals("") ) {			sSQLs+="	AND Oent_Type='"+sSGB+"' \n";		}		if( !sCompName.equals("") ) {			sSQLs+="	AND Oent_Name LIKE '%"+sCompName+"%' \n";		}		if( !sCompNo.equals("") ) {			sSQLs+="	AND Mng_No='"+sCompNo+"' \n";		}		if( !sCYear.equals("") ) {			sSQLs+="	AND Current_Year='"+sCYear+"' \n";		}		sSQLs+="GROUP BY Oent_Name,Mng_No,Oent_GB \n";		sSQLs+="ORDER BY Oent_Name \n";
//System.out.println(sSQLs);
		pstmt = conn.prepareStatement(sSQLs);		rs = pstmt.executeQuery();	  
		while (rs.next()) {			arrOName.add( StringUtil.checkNull(rs.getString("Oent_Name")).trim() );			arrOMngNo.add(StringUtil.checkNull(rs.getString("Mng_No")).trim());			arrOGB.add(StringUtil.checkNull(rs.getString("Oent_GB")).trim());		}		rs.close();		} catch(Exception e) {		e.printStackTrace();	} finally {		if(rs!=null)		try{rs.close();}	catch(Exception e){}		if(pstmt!=null)		try{pstmt.close();}	catch(Exception e){}		if(conn!=null)		try{conn.close();}	catch(Exception e){}		if(resource!=null)	resource.release();	}%><script language="javascript" type="text/javascript" src="/hado/hado/wTools/inc/common_script.js"></script><script type="text/javascript">//<![CDATA[	content = "";		content+="<div id='viewWinTop'>";	content+="	<ul class='lt'>";	content+="		<li class='fr'><a href=javascript:closeViewWin('divView') class='sbutton'>창닫기</a></li>";	content+="	</ul>";	content+="</div>";		content+="<div id='viewWinTitle'>원사업자 검색</div>";	
	content+="<table class='ViewResultTable' align='center'>";	content+="	<tr>";	content+="		<td style='text-align:right;'>검색결과 : <%=arrOName.size()%> 개</td>";	content+="	</tr>";	content+="</table>";	
	content+="<table class='ViewResultTable' align='center'>";	content+="	<tr>";	content+="		<th>순번</th>";	content+="		<th>관리번호</th>";	content+="		<th>원사업자명</th>";	content+="		<th>선택</th>";	content+="	</tr>";	<%for(int j=0;j<arrOName.size(); j++) {%>	content+="	<tr onMouseOver='tbRow_Over(this)' onMouseOut='tbRow_Out(this)'>";	content+="		<td style='text-align:center;'><%=j+1%></td>";	content+="		<td><%=arrOMngNo.get(j)%></td>";	content+="		<td><%=arrOName.get(j)%></td>";	content+="		<td style='text-align:center;'><li class='lt'><a href=javascript:top.selectf('<%=arrOName.get(j)%>','<%=arrOMngNo.get(j)%>','<%=arrOGB.get(j)%>');>선택</a></li></td>";	content+="	</tr>";	<%}%>	content+="</table>";	
	content+="<div id='divViewWinbutton'>";	content+="	<ul class='lt'>";	content+="		<li class='fr'><a href=javascript:closeViewWin('divView') class='sbutton'>창닫기</a></li>";	content+="	</ul>";	content+="</div>";	
	top.document.getElementById("divView").innerHTML = content;	top.setNowProcessFalse();//]]</script>